### ISSUE TITLE
Initiative-Supporter `SHOW` Bug - 'Cast to ObjectId failed for value "test" at path "_id" for model "User"'

### ISSUE THREAD

**Issue by Beacon24** [Beacon24/v0#5]
User can successfully "join" initiatives as a supporter, but initiative `show.ejs` page will not load, gives 'Cast to ObjectID' error. 

Seems to be taking username (test) and using it instead of objectId? But I cannot figure out why.

Also, maybe of importance, when I check the test initiative in my Mongo database with `db.initiatives.find().pretty()` I see that the user objectId number has successfully been added to the `supporters` array, but that there is also an entry of `null` that comes first.

**Comment by poppypiney** [comment]
inside /controllers/initiatives.js line 29, 30
```
    initiative.leaders.push(req.user_id)
    initiative.supporters.push(req.user_id)
```
might need to be changed to this
```
    initiative.leaders.push(req.user._id)
    initiative.supporters.push(req.user._id)
```

I am not so sure this would be the same bug because I don't find the 'Cast to ObjectId' popped in

**Comment by Beacon24** [comment]
Good find, thanks! I fixed this and committed the changes, but yes seems like the bug persists.

**Comment by Beacon24** [comment]
Problem was with supporters not being fully defined, I think. At any rate I believe its fixed now, will see what happens when I add supporters reference back in.
