### ISSUE TITLE
node_modules folder is submitted to the repo

### ISSUE THREAD

**Issue by poppypiney** [Beacon24/v0#7]
today, I have tried to set up your project on my local and found that there is node_modules folder in the repo. Do you want to keep it this way or forget to remove it?

**Comment by lukebelliveau** [comment]
good catch @poppypiney, here's a PR to fix: https://github.com/Beacon24/v0/pull/8

@Beacon24 i'll leave that PR up for you to approve

**Comment by Beacon24** [comment]
Approved, yes I forgot to remove it, or rather didn't realize I needed to! Good catch, thank you both!
